# Site settings
title: Renan Miranda
description: Página Pessoal de Renan Miranda
keywords: Modern, Blogging, Fun
author: Renan Miranda
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
