# Site settings
title: Meus Pojetos
description: Plataforma de notas
keywords: Renan notas
author: Renan
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
